"""Core data models and configuration."""

from .models import (
    Medium,
    Category,
    LogProfile,
    AudioEventType,
    BoundingBox,
    Face,
    VideoMetadata,
    Video,
    Frame,
    AudioEvent,
    ClipSuggestion,
    ExportSettings,
    AnalysisState,
    Project,
)
from .config import (
    VIDEO_EXTENSIONS,
    CROP_PRESETS,
    CATEGORY_WEIGHTS,
    DEFAULT_QUOTAS,
    JPEG_QUALITY,
    VIDEO_CRF,
    DEFAULT_CONFIG_DIR,
    DEFAULT_LOG_DIR,
)
from .exceptions import (
    SSTError,
    VideoNotFoundError,
    UnsupportedFormatError,
    FFmpegError,
    ModelLoadError,
    NoFacesFoundError,
    AudioExtractionError,
    AnalysisError,
    ExportError,
)

__all__ = [
    # Models
    'Medium',
    'Category', 
    'LogProfile',
    'AudioEventType',
    'BoundingBox',
    'Face',
    'VideoMetadata',
    'Video',
    'Frame',
    'AudioEvent',
    'ClipSuggestion',
    'ExportSettings',
    'AnalysisState',
    'Project',
    # Config
    'VIDEO_EXTENSIONS',
    'CROP_PRESETS',
    'CATEGORY_WEIGHTS',
    'DEFAULT_QUOTAS',
    'JPEG_QUALITY',
    'VIDEO_CRF',
    'DEFAULT_CONFIG_DIR',
    'DEFAULT_LOG_DIR',
    # Exceptions
    'SSTError',
    'VideoNotFoundError',
    'UnsupportedFormatError',
    'FFmpegError',
    'ModelLoadError',
    'NoFacesFoundError',
    'AudioExtractionError',
    'AnalysisError',
    'ExportError',
]
